<a href="https://colab.research.google.com/github/Neha9492/Bangladesh-Real-Estate/blob/main/RealEstateBangladesh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import relevant libraries and the data file

In [66]:
import pandas as pd
import numpy as np

In [67]:
valDf = pd.read_csv('./naveenkumar_propertyfinderbd.csv')

##Sneak peek into the original data file

In [68]:
valDf.head()

added_on  \
0   Thu, Apr 6, 2023 7:49 PM   
1   Sun, Apr 9, 2023 9:21 AM   
2  Wed, Mar 22, 2023 8:42 AM   
3  Mon, Mar 20, 2023 5:55 AM   
4   Wed, Apr 5, 2023 5:50 AM   

                                             address  \
0          CHETONA TOWER, 274/4, Mirpur 60 fit road.   
1                                     Gulshan Avenue   
2  JCX TOWER,1136/A, Block-I, Level 5, Japan Stre...   
3                                     Gulshan Avenue   
4  Sardar Complex, 1 South komlapur. Motijheel, D...   

                                  area  \
0                        Mirpur, Dhaka   
1                Gulshan Avenue, Dhaka   
2  Bashundhara Residential Area, Dhaka   
3                Gulshan Avenue, Dhaka   
4                     Motijheel, Dhaka   

                                             details fire_exit    generator  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...       NaN          NaN   
1  Gulshan avenue is the most expensive and sough...       Yes          NaN   
2  Two Room Furnished Serviced Apartment RENT in ...       Yes  Full Backup   
3  Fully furnished 7000 sft office available for ...       Yes  Full Backup   
4                                         open space       NaN  Full Backup   

   gym                last_updated lift offered_floor  ... property_category  \
0  NaN    Sun, Apr 9, 2023 5:12 AM  NaN             5  ...       Residential   
1  NaN    Sun, Apr 9, 2023 9:21 AM  Yes             5  ...        Commercial   
2  NaN  Sat, Mar 25, 2023 10:26 AM  Yes             4  ...       Residential   
3  NaN   Mon, Mar 20, 2023 5:55 AM  Yes             7  ...        Commercial   
4  NaN   Sat, Apr 8, 2023 11:46 AM  NaN             1  ...        Commercial   

  property_id property_size      property_type  \
0         864          1200          Apartment   
1         875          2500       Office Space   
2         821           375  Service Apartment   
3         815          7000             Office   
4         856          9000      Factory Shade   

                                        property_url  rent_or_sale  \
0  https://propertyfinderbd.com/property-details/864          Sale   
1  https://propertyfinderbd.com/property-details/875          Rent   
2  https://propertyfinderbd.com/property-details/821          Rent   
3  https://propertyfinderbd.com/property-details/815          Rent   
4  https://propertyfinderbd.com/property-details/856          Rent   

  rooftop_garden swimming_pool  \
0            NaN           NaN   
1            Yes           NaN   
2            NaN           NaN   
3            Yes           NaN   
4            NaN           NaN   

                                               title total_bathrooms  
0  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...               3  
1   2500 sft office space for rent in Gulshan Avenue             NaN  
2  Two Room Furnished Serviced Apartment RENT in ...               1  
3  Ready Fully furnished 7,000 sft office for ren...             NaN  
4                              Office space for rent              10  

[5 rows x 23 columns]

In [69]:
valDf.info()
valDf.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   added_on           555 non-null    object
 1   address            555 non-null    object
 2   area               555 non-null    object
 3   details            555 non-null    object
 4   fire_exit          249 non-null    object
 5   generator          505 non-null    object
 6   gym                58 non-null     object
 7   last_updated       555 non-null    object
 8   lift               294 non-null    object
 9   offered_floor      491 non-null    object
 10  parking            396 non-null    object
 11  present_status     555 non-null    object
 12  price              555 non-null    object
 13  property_category  555 non-null    object
 14  property_id        555 non-null    int64 
 15  property_size      555 non-null    int64 
 16  property_type      555 non-null    object
 1

property_id  property_size
count   555.000000   5.550000e+02
mean    383.983784   2.539706e+04
std     239.644234   9.207220e+04
min      22.000000   0.000000e+00
25%     170.500000   1.362500e+03
50%     364.000000   3.000000e+03
75%     583.000000   1.591250e+04
max     875.000000   1.180800e+06

##Replace the original column names with the column names given as project standard

In [70]:
valDf.rename(columns = {'property_size':'AREA'}, inplace = True)
valDf.rename(columns = {'rent_or_sale':'PURPOSE'}, inplace = True)
valDf.rename(columns = {'property_overview':'TITLE'}, inplace = True)
valDf.rename(columns = {'property_description':'DETAILS'}, inplace = True)
valDf.rename(columns = {'property_category':'BUILDING_NATURE'}, inplace = True)
valDf.rename(columns = {'property_type':'BUILDING_TYPE'}, inplace = True)
valDf.rename(columns = {'num_bath_rooms':'TOTAL_BATHROOMS'}, inplace = True)
valDf.rename(columns = {'fire_exit':'K1'}, inplace = True)
valDf.rename(columns = {'generator':'K2'}, inplace = True)
valDf.rename(columns = {'gym':'K3'}, inplace = True)
valDf.rename(columns = {'lift':'K4'}, inplace = True)
valDf.rename(columns = {'offered_floor':'K5'}, inplace = True)
valDf.rename(columns = {'parking':'K6'}, inplace = True)
valDf.rename(columns = {'present_status':'K7'}, inplace = True)
valDf.rename(columns = {'rooftop_garden':'K8'}, inplace = True)
valDf.rename(columns = {'swimming_pool':'K9'}, inplace = True)


In [71]:
valDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   added_on         555 non-null    object
 1   address          555 non-null    object
 2   area             555 non-null    object
 3   details          555 non-null    object
 4   K1               249 non-null    object
 5   K2               505 non-null    object
 6   K3               58 non-null     object
 7   last_updated     555 non-null    object
 8   K4               294 non-null    object
 9   K5               491 non-null    object
 10  K6               396 non-null    object
 11  K7               555 non-null    object
 12  price            555 non-null    object
 13  BUILDING_NATURE  555 non-null    object
 14  property_id      555 non-null    int64 
 15  AREA             555 non-null    int64 
 16  BUILDING_TYPE    555 non-null    object
 17  property_url     555 non-null    ob

##Get the District, city data by splitting the area column
##Feeding the country column with default as Bangladesh

In [72]:
valDf['DISTRICT']=valDf['area'].str.split(',').str[0]
valDf['CITY']=valDf['area'].str.split(',').str[1]
valDf['OTHERZONEAREA']=valDf['address'].str.split(',').str[-1]
valDf['COUNTRY']='Bangladesh'
valDf.head()

added_on  \
0   Thu, Apr 6, 2023 7:49 PM   
1   Sun, Apr 9, 2023 9:21 AM   
2  Wed, Mar 22, 2023 8:42 AM   
3  Mon, Mar 20, 2023 5:55 AM   
4   Wed, Apr 5, 2023 5:50 AM   

                                             address  \
0          CHETONA TOWER, 274/4, Mirpur 60 fit road.   
1                                     Gulshan Avenue   
2  JCX TOWER,1136/A, Block-I, Level 5, Japan Stre...   
3                                     Gulshan Avenue   
4  Sardar Complex, 1 South komlapur. Motijheel, D...   

                                  area  \
0                        Mirpur, Dhaka   
1                Gulshan Avenue, Dhaka   
2  Bashundhara Residential Area, Dhaka   
3                Gulshan Avenue, Dhaka   
4                     Motijheel, Dhaka   

                                             details   K1           K2   K3  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...  NaN          NaN  NaN   
1  Gulshan avenue is the most expensive and sough...  Yes          NaN  NaN   
2  Two Room Furnished Serviced Apartment RENT in ...  Yes  Full Backup  NaN   
3  Fully furnished 7000 sft office available for ...  Yes  Full Backup  NaN   
4                                         open space  NaN  Full Backup  NaN   

                 last_updated   K4 K5  ...  \
0    Sun, Apr 9, 2023 5:12 AM  NaN  5  ...   
1    Sun, Apr 9, 2023 9:21 AM  Yes  5  ...   
2  Sat, Mar 25, 2023 10:26 AM  Yes  4  ...   
3   Mon, Mar 20, 2023 5:55 AM  Yes  7  ...   
4   Sat, Apr 8, 2023 11:46 AM  NaN  1  ...   

                                        property_url PURPOSE   K8   K9  \
0  https://propertyfinderbd.com/property-details/864    Sale  NaN  NaN   
1  https://propertyfinderbd.com/property-details/875    Rent  Yes  NaN   
2  https://propertyfinderbd.com/property-details/821    Rent  NaN  NaN   
3  https://propertyfinderbd.com/property-details/815    Rent  Yes  NaN   
4  https://propertyfinderbd.com/property-details/856    Rent  NaN  NaN   

                                               title  total_bathrooms  \
0  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...                3   
1   2500 sft office space for rent in Gulshan Avenue              NaN   
2  Two Room Furnished Serviced Apartment RENT in ...                1   
3  Ready Fully furnished 7,000 sft office for ren...              NaN   
4                              Office space for rent               10   

                       DISTRICT    CITY         OTHERZONEAREA     COUNTRY  
0                        Mirpur   Dhaka   Mirpur 60 fit road.  Bangladesh  
1                Gulshan Avenue   Dhaka        Gulshan Avenue  Bangladesh  
2  Bashundhara Residential Area   Dhaka       Bashundhara R/A  Bangladesh  
3                Gulshan Avenue   Dhaka        Gulshan Avenue  Bangladesh  
4                     Motijheel   Dhaka                 Dhaka  Bangladesh  

[5 rows x 27 columns]

##Looking up unique values of the field to see if there are any null or junk values

In [73]:
valDf['BUILDING_NATURE'].unique()

array(['Residential', 'Commercial', 'Land', 'None'], dtype=object)

In [74]:
valDf['BUILDING_TYPE'].unique()

array(['Apartment', 'Office Space', 'Service Apartment', 'Office',
       'Factory Shade', 'Commercial Plot', 'Commercial Building',
       'Industrial Plot', 'Ready Flat', 'Plot', 'Building', 'House',
       'Open Field', 'Factory Land', 'High Land', 'Factory Building',
       'Factory Sale', 'Apartment Office', 'Warehouse',
       'Building For Office', 'Furnished', 'Floor', 'Land with building',
       'Office Building', 'Brand New Apartment', 'Show-room',
       'Duplex House', 'None', 'Resorts / Banglobari', 'Duplex Apartment',
       'Open Floor', 'Semi Commercial Apartment'], dtype=object)

In [75]:
valDf['PURPOSE'].unique()

array(['Sale', 'Rent'], dtype=object)

In [76]:
valDf['K1'].unique()


array([nan, 'Yes'], dtype=object)

In [77]:
valDf['K2'].unique()


array([nan, 'Full Backup', 'No', 'Partial'], dtype=object)

In [78]:
valDf['K3'].unique()


array([nan, 'Yes'], dtype=object)

In [79]:
valDf['K4'].unique()


array([nan, 'Yes'], dtype=object)

In [80]:
valDf['K5'].unique()


array(['5', '4', '7', '1', nan, '3', '9', '2', '6', '18', '19', '11',
       '17', '10', '30+', '16', '12', '15', '13'], dtype=object)

In [81]:
valDf['K6'].unique()


array([nan, '2 Slot', '1 Slot', '4 Slot', '20 Slot', '5 Slot', '7 Slot',
       '3 Slot', '6 Slot', 'N/A Slot', '8 Slot', '১ Slot', '10+ Slot',
       '10 Slot', '50 Slot', '28 Slot',
       '2 level of basement Parking Slot', '14 Slot', '12 Slot',
       '20+ Slot', '5/7 Slot', '1216 Slot', '37 Slot'], dtype=object)

In [82]:
valDf['K7'].unique()


array(['Vacant', 'Hired'], dtype=object)

In [83]:
valDf['K8'].unique()


array([nan, 'Yes'], dtype=object)

In [84]:
valDf['K9'].unique()

array([nan, 'Yes'], dtype=object)

In [85]:
valDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   added_on         555 non-null    object
 1   address          555 non-null    object
 2   area             555 non-null    object
 3   details          555 non-null    object
 4   K1               249 non-null    object
 5   K2               505 non-null    object
 6   K3               58 non-null     object
 7   last_updated     555 non-null    object
 8   K4               294 non-null    object
 9   K5               491 non-null    object
 10  K6               396 non-null    object
 11  K7               555 non-null    object
 12  price            555 non-null    object
 13  BUILDING_NATURE  555 non-null    object
 14  property_id      555 non-null    int64 
 15  AREA             555 non-null    int64 
 16  BUILDING_TYPE    555 non-null    object
 17  property_url     555 non-null    ob

valDf['swimming_pool'].unique()
valDf['swimming_pool']=valDf['swimming_pool'].replace(['Yes'],'1')